get the real exit code of the mvn command (the first in the pipe)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -33,11 +33,14 @@ jobs:
         run: |
           mkdir target
           mvn -U -B validate -P sxda-license-validation 2>&1 | tee target/license-headers-validation.txt
-          EXIT_CODE=$?
+          EXIT_CODE=${PIPESTATUS[0]}
           cat target/license-headers-validation.txt | grep -E '\[(WARNING|ERROR)\]' > target/license-headers-validation-warnings.txt
           cat target/license-headers-validation.txt | grep 'goal com.mycila:license-maven-plugin' | sed 's/^\[\([^]]*\)\] //' > target/license-headers-validation-summary.txt
           if [ $EXIT_CODE -eq 0 ] && [ ! -s target/license-headers-validation-summary.txt ]; then
             echo "No license header validation errors detected." > target/license-headers-validation-summary.txt
+            echo "conclusion=success" >> $GITHUB_OUTPUT
+          else
+            echo "conclusion=failure" >> $GITHUB_OUTPUT
           fi
           echo "result=$(cat target/license-headers-validation-summary.txt)" >> $GITHUB_OUTPUT
           exit $EXIT_CODE
@@ -47,7 +50,7 @@ jobs:
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           name: Validate license headers
-          conclusion: ${{ job.status }}
+          conclusion: ${{ steps.validate-license-headers.outputs.conclusion }}
           output_text_description_file: target/license-headers-validation-warnings.txt
           output: |
             {"summary":"${{ steps.validate-license-headers.outputs.result }}"}
