Feature/use eclipse scout definitions (#6)
* use version from eclipse scout, versioning schema updated

* validate license headers

* fetch full repo to get history for license header validation, use RUNNER_TEMP dir for temp file

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -17,6 +17,9 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
+        with:
+          # we need the full history to validate license headers
+          fetch-depth: 0
 
       - uses: actions/setup-java@v4
         with:
@@ -24,6 +27,33 @@ jobs:
           distribution: 'temurin'
           cache: maven
           server-id: github
+
+      - name: Validate license headers
+        id: validate-license-headers
+        run: |
+          mkdir target
+          mvn -U -B validate -P sxda-license-validation 2>&1 | tee target/license-headers-validation.txt
+          EXIT_CODE=${PIPESTATUS[0]}
+          cat target/license-headers-validation.txt | grep -E '\[(WARNING|ERROR)\]' > target/license-headers-validation-warnings.txt
+          cat target/license-headers-validation.txt | grep 'goal com.mycila:license-maven-plugin' | sed 's/^\[\([^]]*\)\] //' > target/license-headers-validation-summary.txt
+          if [ $EXIT_CODE -eq 0 ] && [ ! -s target/license-headers-validation-summary.txt ]; then
+            echo "No license header validation errors detected." > target/license-headers-validation-summary.txt
+            echo "conclusion=success" >> $GITHUB_OUTPUT
+          else
+            echo "conclusion=failure" >> $GITHUB_OUTPUT
+          fi
+          echo "result=$(cat target/license-headers-validation-summary.txt)" >> $GITHUB_OUTPUT
+          exit $EXIT_CODE
+
+      - uses: LouisBrunner/checks-action@v1.6.1
+        if: always() && github.event_name == 'pull_request'
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          name: Validate license headers
+          conclusion: ${{ steps.validate-license-headers.outputs.conclusion }}
+          output_text_description_file: target/license-headers-validation-warnings.txt
+          output: |
+            {"summary":"${{ steps.validate-license-headers.outputs.result }}"}
 
       - name: Build with Maven
         run: mvn -B package --file pom.xml --fail-at-end --no-transfer-progress
